/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chi.shiftRight;
import chi.shiftRight.scheduler.Shift.DayShift;
import chi.shiftRight.scheduler.Shift.TimeShift;
import chi.shiftRight.scheduler.Shift.WeekShift;
import chi.shiftRight.scheduler.ShiftFactory.WeekShiftFactory;
import chi.shiftRight.scheduler.calc.IDGenerator;
import chi.shiftRight.scheduler.staff.Employees;
import java.util.ArrayList;
import java.util.Arrays;

public class ShiftRightMain extends javax.swing.JFrame {
    
    
    StringBuilder wholeText = new StringBuilder();

    /**
     * Creates new form MainMenu
     */
    public ShiftRightMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rerunBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ShiftRight - Main Menu");

        rerunBtn.setToolTipText("");
        rerunBtn.setLabel("Run");
        rerunBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rerunBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rerunBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rerunBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 343, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rerunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerunBtnActionPerformed
    
    wholeText.setLength(0);
    
    IDGenerator.resetStaffCounter();
    ArrayList<WeekShift> oneWeekShift = new WeekShiftFactory().getWeekList();
    
        System.out.println("Size of weekshift : " + oneWeekShift.size());
        
        ArrayList<String> daysInWeek = new ArrayList<>(Arrays.asList("Monday", "Tuesday", "Wedneaday", "Thursday", "Friday", "Saturday", "Sunday"));
        ArrayList<String> shiftType = new ArrayList<>(Arrays.asList("Morning 8:00 - 16:00", "Evening 16:00 - 00:00", "Night 00:00 - 08.00"));
        
        int dayCounter = 0;
        int shiftCounter = 0;
        
        wholeText.append("<h1 align=\"center\">").append("Staff schedule for this week").append("</h1>");
        
        for (WeekShift week : oneWeekShift){
            
            for (DayShift day : week.getDayList()){
                wholeText.append("<h1>").append(daysInWeek.get(dayCounter++)).append("</h1>").append("\n");
                
                for (TimeShift shift : day.getShiftList()){                    
                    wholeText.append("<h2>").append(shiftType.get(shiftCounter++)).append("</h2>").append("\n");
                    
                    for (Employees employee: shift.getShiftStaffList()){
                        wholeText.append("<p style=\"font-size:12px\">").append(employee.getEmployeeDetails()).append("<p>").append("\n");
                    }    
                }
            shiftCounter = 0;
            }
        }
    jTextPane1.setText(wholeText.toString());
    jTextPane1.setCaretPosition(0);
    rerunBtn.setText("Re-run");
    }//GEN-LAST:event_rerunBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
          jTextPane1.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShiftRightMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShiftRightMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShiftRightMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShiftRightMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShiftRightMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton rerunBtn;
    // End of variables declaration//GEN-END:variables
}
